// localization/en.js
export default {
  home: 'Home',
  welcome: "Welcome to MoviesApp",
  searchPlaceholder: "Search for a movie",
  watchlist: "Watchlist",
  logout: "Logout",
  account: "Account",
  darkMode: "Dark Mode",
  genre: "Select Genre",
  email: "Email",
  password: "Password",
  login: "Login",
  signup: "Sign Up",
  accountDetails: "Account Details",
  personalInformation: "Personal Information",
  email: "Email",
  name: "Name",
  yourName: "Your name",
  passwordUpdate: "Password Update",
  currentPassword: "Current Password (required for changes)",
  enterCurrentPassword: "Enter current password",
  newPassword: "New Password",
  enterNewPassword: "Enter new password",
  confirmNewPassword: "Confirm New Password",
  saveChanges: "Save Changes",
  updating: "Updating...",
  releasedOn: "Released on",
  yetToReleaseOn: "Yet to release on",
  noOverviewAvailable: "No overview available.",
  noTrailerAvailable: "No trailer available",
  unknown: "Unknown"
};
